baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Sites"
theme = "ananke"
sectionPagesMenu = "main"
[[menu.main]]
 name = "Home"
 url  = "/"
 weight = 0

[[menu.main]]
 name = "About"
 url  = "../about"
 weight = 5

[[menu.main]]
 name = "Blog"
 url  = "../posts/"
 weight = 10
